// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shop.proto

package shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetShopInfoReq) Validate() error {
	return nil
}
func (this *GetShopInfoRes) Validate() error {
	return nil
}
func (this *RegisterShopReq) Validate() error {
	if !(this.UserID > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("UserID", fmt.Errorf(`value '%v' must be greater than '0'`, this.UserID))
	}
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	if this.Address == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Address", fmt.Errorf(`value '%v' must not be an empty string`, this.Address))
	}
	return nil
}
func (this *RegisterShopResp) Validate() error {
	return nil
}
